# How to import dataset in python using pandas libraries
Written by: Muhammad Shoaib\
Date: 02.12.2025\
Email:shoaibxdev9@gmail.com

In [ ]:
# Step.1
# importing library
import pandas as pd

In [ ]:
# Step.2
#reading / importing datasets
df = pd.read_excel("pandas_01_day6.xlsx")

In [ ]:
df.tail(10)

   Height Weight Favourite Dish
77    5.5     85        Biryani
78   5’11     72  Karahi Ghosht
79    5'3     62        Biryani
80    5.4     55          Pasta
81    5.5     52  Karahi Ghosht
82    5.4     55          Pasta
83    5.9   75KG  Karahi Ghosht
84    5.4     61        Biryani
85    6.2     68  Chicken Pulao
86    5.1     96        Biryani

In [ ]:
df.head(10)

  Height Weight Favourite Dish
0    5.8    101  Chicken Pulao
1    6.2     92        Biryani
2    5.9     62  Karahi Ghosht
3    5.9     95  Chicken Pulao
4    5.9     55  Chicken Pulao
5    5.3     59        Biryani
6    5.6     50          Pasta
7    5.9     76        Biryani
8    5.1     78        Biryani
9    5.4     68        Biryani

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Height          87 non-null     object
 1   Weight          87 non-null     object
 2   Favourite Dish  87 non-null     object
dtypes: object(3)
memory usage: 2.2+ KB

In [ ]:
df.body()